[workspace]
authors = ["Bill Chow <19355340+billchow98@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "testing"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
fmt = "clang-format -i src/*.h src/*.cpp test/*.cpp"
start = ".build/tuna"
test = { cmd = "ctest", cwd = ".build/test" }
clean = "ninja -C .build clean"
watch = "watch 'grep -e---- -B6 .build/sprt.log | tail -n8'"
update_baseline = { cmd = "cp all_tests2 all_tests", cwd = ".build" }

[tasks.build]
args = [
  { "arg" = "build_type", "default" = "Release" }
]
cmd = "cmake -G Ninja -S . -B .build -DCMAKE_C_FLAGS=\"\" -DCMAKE_CXX_FLAGS=\"\" -DCMAKE_EXE_LINKER_FLAGS=\"\" -DCMAKE_BUILD_TYPE={{ build_type }} && ninja -C .build"
depends-on = ["fmt"]

[tasks.sprt]
args = [
  { "arg" = "concurrency", "default" = "$(nproc)" }
]
cmd = "cp tuna all_tests2 && ../sprt.sh {{ concurrency }}"
cwd = ".build"
depends-on = ["build"]

[tasks.tournament]
args = [
  { "arg" = "concurrency", "default" = "$(nproc)" }
]
cmd = "cp tuna all_tests2 && python ../tournament.py --concurrency {{ concurrency }}"
cwd = ".build"
depends-on = ["build"]

[dependencies]
cxx-compiler = ">=1.9.0,<2"
cmake = ">=4.0.1,<5"
ninja = ">=1.12.1,<2"
clang-format = ">=20.1.3,<21"
python = ">=3.13.3,<3.14"
