#include "board.h"

#include <cctype>

#include <algorithm>
#include <array>
#include <format>
#include <sstream>
#include <string>

#include "bb.h"
#include "common.h"
#include "eval.h"
#include "hash.h"
#include "lookup.h"
#include "movegen.h"

namespace tuna::board {

const auto STARTPOS_FEN =
    "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";

const auto CASTLING_FEN = "KQkq";

Board::Board() {
    setup_fen(STARTPOS_FEN);
}

void Board::setup(PositionCmd cmd) {
    if (cmd.type == PositionCmd::Startpos) {
        cmd.fen = STARTPOS_FEN;
    }
    setup_fen(cmd.fen);
    for (auto move : cmd.moves) {
        make_move(move);
    }
}

void Board::setup_fen(std::string fen) {
    std::istringstream iss(fen);
    std::fill(piece_on_.begin(), piece_on_.end(), piece::None);
    hash_ = hash::Empty;
    mg_material_ = 0;
    eg_material_ = 0;
    game_phase_ = 0;
    setup_fen_pieces(iss);
    setup_fen_turn(iss);
    setup_fen_castle_flags(iss);
    setup_fen_ep(iss);
    setup_fen_halfmove_clock(iss);
    setup_fen_fullmove_cnt(iss);
    undos_.clear();
    update_infos();
}

std::string Board::debug_str() {
    std::string s;
    for (Rank rk = rank::_8; rk >= rank::_1; rk--) {
        for (File fl = file::A; fl <= file::H; fl++) {
            auto sq = square::init(rk, fl);
            s += debug_char(sq);
        }
        s += '\n';
    }
    s += std::format("turn: {}\n", color::debug_str(turn_));
    s += std::format("ep: {}\n", file::debug_str(ep_));
    s += std::format("castle_flags: {}\n",
                     castle_flags::debug_str(castle_flags_));
    s += std::format("halfmove_clock: {}\n", halfmove_clock_);
    s += std::format("fullmove_cnt: {}\n", fullmove_cnt_);
    s += std::format("hash: 0x{:016x}\n", hash_);
    s += std::format("undos: size() = {}\n", undos_.size());
    s += std::format("checkers:\n{}\n", bb::debug_str(checkers_));
    s += std::format("pinned:\n{}", bb::debug_str(pinned_));
    return s;
}

Bitboard Board::bb(Piece pc, Color cr) {
    return piece_bb_[pc] & color_bb_[cr];
}

Bitboard Board::all() {
    return color_bb_[color::White] | color_bb_[color::Black];
}

Square Board::king_sq(Color sd) {
    return bb::top_sq(bb(piece::King, sd));
}

void Board::make_move(Move move) {
    update_moveinfo(move);
    make_move_start(move);
    remove_to_piece();
    move_from_piece();
    handle_eps();
    handle_promotions();
    handle_castles();
    flip_turn();
    update_infos();
}

void Board::make_null_move() {
    make_move_start(move::Null);
    flip_turn();
    update_infos();
}

void Board::unmake_move() {
    auto &undo = undos_.back();
    flip_turn();
    unmake_move_main(undo);
    unmake_move_end(undo);
    undos_.pop_back();
}

void Board::unmake_null_move() {
    auto &undo = undos_.back();
    flip_turn();
    restore_ep(undo.ep);
    halfmove_clock_ = undo.halfmove_clock;
    if (turn_ == color::Black) {
        fullmove_cnt_--;
    }
    assert(hash_ == undo.hash);
    checkers_ = undo.checkers;
    pinned_ = undo.pinned;
    undos_.pop_back();
}

Bitboard Board::single_pushes(Bitboard pawns) {
    return bb::shift(pawns, dir::N, turn_) & ~all();
}

Bitboard Board::double_pushes(Bitboard pawns) {
    pawns &= rank_2();
    auto tos = bb::shift(pawns, dir::N, turn_) & ~all();
    return bb::shift(tos, dir::N, turn_) & ~all();
}

Bitboard Board::evasion_mask() {
    auto checker = bb::top_sq(checkers_);
    auto ksq = bb::top_sq(bb(piece::King, turn_));
    return lookup::in_between(checker, ksq) | checkers_;
}

// Test if TT move is valid
// Assumes the move is one that can be generated by MoveGenerator
bool Board::is_pseudo_legal(Move move) {
    update_moveinfo(move);
    if (is_ep() || is_promotion() || is_castle()) {
        return movegen::is_legal_move(*this, move);
    }
    auto from_bb = bb::from_sq(mi_.from);
    auto to_bb = bb::from_sq(mi_.to);
    if ((color_bb_[turn_] & from_bb) == bb::Empty ||
        (color_bb_[turn_] & to_bb) != bb::Empty) {
        return false;
    }
    if (!is_pseudo_legal_attack()) {
        return false;
    }
    return checkers_ == bb::Empty || is_pseudo_legal_evasion();
}

bool Board::is_legal(Move move) {
    update_moveinfo(move);
    auto ksq = bb::top_sq(bb(piece::King, turn_));
    if (mi_.from == ksq) {
        if (king_to_is_attacked(ksq)) {
            return false;
        }
        if (!is_legal_castle()) {
            return false;
        }
        return true;
    }
    if (is_pinned() && !is_on_line(ksq, mi_.from, mi_.to)) {
        return false;
    }
    if (is_ep()) {
        return is_legal_ep(ksq);
    }
    return true;
}

bool Board::in_check() {
    return checkers_ != bb::Empty;
}

bool Board::is_capture(Move move) {
    update_moveinfo(move);
    // Captures + queen promotions (same as movegen captures)
    return mi_.promotion == piece::Queen ||
           (all() & bb::from_sq(mi_.to)) != bb::Empty || is_ep();
}

// Does not detect stalemate
bool Board::is_draw() {
    return is_fifty_move_draw() || is_repetition_draw();
}

Bitboard Board::color_bb(Color sd) {
    return color_bb_[sd];
}

Piece Board::piece_on(Square sq) {
    return piece_on_[sq];
}

Color Board::turn() {
    return turn_;
}

File Board::ep() {
    return ep_;
}

Hash Board::hash() {
    return hash_;
}

i32 Board::checkers_count() {
    return bb::popcnt(checkers_);
}

Score Board::mg_material() {
    return mg_material_;
}

Score Board::eg_material() {
    return eg_material_;
}

i32 Board::game_phase() {
    return game_phase_;
}

void Board::update_moveinfo(Move move) {
    mi_.from = move::from(move);
    mi_.to = move::to(move);
    mi_.promotion = move::promotion(move);
    mi_.from_pc = piece_on_[mi_.from];
    mi_.to_pc = piece_on_[mi_.to];
    mi_.from_rk = square::rank(mi_.from);
    mi_.to_rk = square::rank(mi_.to);
    mi_.from_fl = square::file(mi_.from);
    mi_.to_fl = square::file(mi_.to);
}

void Board::create_undo(Move move) {
    UndoInfo undo;
    undo.move = move;
    // Corner case: en passant move.
    // But captured_piece == piece::None will not be an issue.
    undo.captured_piece = piece_on_[move::to(move)];
    undo.ep = ep_;
    undo.castle_flags = castle_flags_;
    undo.halfmove_clock = halfmove_clock_;
    undo.hash = hash_;  // Needed for repetition detection for now
    undo.checkers = checkers_;
    undo.pinned = pinned_;
    undos_.push_back(undo);
}

void Board::clear_ep() {
    if (ep_ != file::None) {
        hash_ ^= hash::ep[ep_];
        ep_ = file::None;
    }
}

void Board::make_turn() {
    clear_ep();
    halfmove_clock_++;
    if (turn_ == color::Black) {
        fullmove_cnt_++;
    }
}

void Board::make_move_start(Move move) {
    create_undo(move);
    make_turn();
}

void Board::flip_piece(Color sd, Piece pc, Square sq) {
    auto delta_bb = bb::from_sq(sq);
    piece_bb_[pc] ^= delta_bb;
    color_bb_[sd] ^= delta_bb;
    hash_ ^= hash::piece[sd][pc][sq];
}

void Board::remove_piece(Color sd, Piece pc, Square sq) {
    flip_piece(sd, pc, sq);
    piece_on_[sq] = piece::None;
    mg_material_ -= eval::mg_piece_value(sd, pc, sq);
    eg_material_ -= eval::eg_piece_value(sd, pc, sq);
    game_phase_ -= eval::piece_phase(pc);
}

void Board::add_piece(Color sd, Piece pc, Square sq) {
    flip_piece(sd, pc, sq);
    piece_on_[sq] = pc;
    mg_material_ += eval::mg_piece_value(sd, pc, sq);
    eg_material_ += eval::eg_piece_value(sd, pc, sq);
    game_phase_ += eval::piece_phase(pc);
}

void Board::move_piece(Color sd, Piece pc, Square from, Square to) {
    remove_piece(sd, pc, from);
    add_piece(sd, pc, to);
}

void Board::move_from_piece() {
    move_piece(turn_, mi_.from_pc, mi_.from, mi_.to);
    if (mi_.from_pc == piece::Pawn || mi_.to_pc != piece::None) {
        halfmove_clock_ = 0;
    }
}

void Board::remove_to_piece() {
    if (mi_.to_pc != piece::None) {
        remove_piece(!turn_, mi_.to_pc, mi_.to);
    }
}

bool Board::is_double_push() {
    return mi_.from_pc == piece::Pawn && abs(mi_.to_rk - mi_.from_rk) == 2;
}

bool Board::is_ep() {
    return mi_.from_pc == piece::Pawn && mi_.from_fl != mi_.to_fl &&
           mi_.to_pc == piece::None;
}

void Board::set_ep(File fl) {
    assert(ep_ == file::None);
    ep_ = fl;
    hash_ ^= hash::ep[fl];
}

// Handles board.ep (double push) and ep captures
void Board::handle_eps() {
    if (is_double_push()) {
        auto ep_fl = square::file(mi_.from);
        set_ep(ep_fl);
    } else if (is_ep()) {
        auto ep_sq = mi_.to ^ 8;
        remove_piece(!turn_, piece::Pawn, ep_sq);
    }
}

bool Board::is_promotion() {
    return mi_.promotion != piece::None;
}

// Handles promotion to_pc
void Board::handle_promotions() {
    if (is_promotion()) {
        remove_piece(turn_, piece::Pawn, mi_.to);
        add_piece(turn_, mi_.promotion, mi_.to);
    }
}

void Board::remove_castle_flags(CastleFlags cfs) {
    hash_ ^= hash::castling[castle_flags_];
    castle_flags_ &= ~cfs;
    hash_ ^= hash::castling[castle_flags_];
}

void Board::handle_castle_flags() {
    if (mi_.from_pc == piece::Rook) {
        for (Castling c = 0; c < 4; c++) {
            if (mi_.from == CASTLING_INFO[c].rook_from) {
                remove_castle_flags(castle_flags::from_castling(c));
            }
        }
    } else if (mi_.from_pc == piece::King) {
        namespace cf = castle_flags;
        auto cfs = turn_ == color::White ? cf::WhiteAll : cf::BlackAll;
        remove_castle_flags(cfs);
    }
    for (Castling c = 0; c < 4; c++) {
        if (mi_.to == CASTLING_INFO[c].rook_from) {
            remove_castle_flags(castle_flags::from_castling(c));
        }
    }
}

bool Board::is_castle() {
    return mi_.from_pc == piece::King && abs(mi_.to_fl - mi_.from_fl) == 2;
}

void Board::handle_castle_moves() {
    if (is_castle()) {
        for (Castling c = 0; c < 4; c++) {
            if (mi_.to == CASTLING_INFO[c].king_to) {
                auto rook_from = CASTLING_INFO[c].rook_from;
                auto rook_to = CASTLING_INFO[c].rook_to;
                move_piece(turn_, piece::Rook, rook_from, rook_to);
            }
        }
    }
}

// Handles castling moves (king/rook moved / opp rook captured) and
// castling moves (move rook)
void Board::handle_castles() {
    handle_castle_flags();
    handle_castle_moves();
}

void Board::flip_turn() {
    turn_ = !turn_;
    hash_ ^= hash::side;
}

// sd: color of attackers
Bitboard Board::pawn_attacks_from(Square sq, Color sd) {
    using namespace dir;
    auto sq_bb = bb::from_sq(sq);
    auto sh = [this](Bitboard bb, Direction d) {
        return bb::shift(bb, d, turn_);
    };
    return color_bb_[sd] & (sd == turn_ ? sh(sq_bb, SW) | sh(sq_bb, SE)
                                        : sh(sq_bb, NW) | sh(sq_bb, NE));
}

Bitboard Board::attacks_from(Piece pc, Square sq) {
    if (pc == piece::Pawn) {
        return pawn_attacks_from(sq, color::White) |
               pawn_attacks_from(sq, color::Black);
    } else {
        return lookup::attacks(pc, sq, all());
    }
}

Bitboard Board::attackers_to(Square sq) {
    auto all_atkrs = bb::Empty;
#pragma GCC unroll 6
    for (Piece pc = piece::Pawn; pc <= piece::King; pc++) {
        all_atkrs |= attacks_from(pc, sq) & piece_bb_[pc];
    }
    all_atkrs &= all();
    return all_atkrs;
}

void Board::update_checkers() {
    checkers_ = attackers_to(king_sq(turn_)) & color_bb_[!turn_];
}

Bitboard Board::bishop_likes() {
    return piece_bb_[piece::Bishop] | piece_bb_[piece::Queen];
}

Bitboard Board::rook_likes() {
    return piece_bb_[piece::Rook] | piece_bb_[piece::Queen];
}

void Board::update_pinned() {
    pinned_ = bb::Empty;
    auto ksq = king_sq(turn_);
    auto xrays = lookup::attacks(piece::Bishop, ksq) & bishop_likes() |
                 lookup::attacks(piece::Rook, ksq) & rook_likes();
    xrays &= color_bb_[!turn_];
    auto occ = all() ^ xrays;
    while (xrays) {
        auto xray = bb::next_sq(xrays);
        auto bb = lookup::in_between(ksq, xray) & occ;
        if (bb::popcnt(bb) == 1) {
            pinned_ |= bb;  // might repeat same sq
        }
    }
}

void Board::update_infos() {
    update_checkers();
    update_pinned();
}

bool Board::is_undo_castle() {
    return mi_.to_pc == piece::King && abs(mi_.to_fl - mi_.from_fl) == 2;
}

void Board::undo_castles() {
    if (is_undo_castle()) {
        for (Castling c = 0; c < 4; c++) {
            if (mi_.to == CASTLING_INFO[c].king_to) {
                auto rook_from = CASTLING_INFO[c].rook_from;
                auto rook_to = CASTLING_INFO[c].rook_to;
                move_piece(turn_, piece::Rook, rook_to, rook_from);
            }
        }
    }
}

bool Board::is_undo_promotion() {
    return is_promotion();
}

void Board::undo_promotions() {
    if (is_undo_promotion()) {
        remove_piece(turn_, mi_.promotion, mi_.to);
        add_piece(turn_, piece::Pawn, mi_.to);
        mi_.to_pc = piece::Pawn;
    }
}

bool Board::is_undo_ep(Piece captured) {
    return mi_.to_pc == piece::Pawn && mi_.from_fl != mi_.to_fl &&
           captured == piece::None;
}

void Board::undo_eps(Piece captured) {
    if (is_undo_ep(captured)) {
        auto ep_sq = mi_.to ^ 8;
        add_piece(!turn_, piece::Pawn, ep_sq);
    }
}

void Board::add_to_piece(Piece captured) {
    if (captured != piece::None) {
        add_piece(!turn_, captured, mi_.to);
    }
}

void Board::undo_move_from_piece() {
    move_piece(turn_, mi_.to_pc, mi_.to, mi_.from);
}

void Board::unmake_move_main(UndoInfo &undo) {
    update_moveinfo(undo.move);
    undo_castles();
    undo_promotions();
    undo_eps(undo.captured_piece);
    undo_move_from_piece();
    add_to_piece(undo.captured_piece);
}

void Board::restore_ep(File ep_fl) {
    clear_ep();
    if (ep_fl != file::None) {
        set_ep(ep_fl);
    }
}

void Board::restore_castle_flags(CastleFlags cfs) {
    remove_castle_flags(castle_flags::All);
    add_castle_flags(cfs);
}

void Board::unmake_move_end(UndoInfo &undo) {
    restore_ep(undo.ep);
    restore_castle_flags(undo.castle_flags);
    halfmove_clock_ = undo.halfmove_clock;
    if (turn_ == color::Black) {
        fullmove_cnt_--;
    }
    assert(hash_ == undo.hash);
    checkers_ = undo.checkers;
    pinned_ = undo.pinned;
}

Bitboard Board::rank_8() {
    return turn_ == color::White ? bb::RANK_8 : bb::RANK_1;
}

Bitboard Board::rank_2() {
    return turn_ == color::White ? bb::RANK_2 : bb::RANK_7;
}

Bitboard Board::pawn_attacks(Bitboard pawns) {
    return bb::shift(pawns, dir::NW, turn_) | bb::shift(pawns, dir::NE, turn_);
}

bool Board::is_pseudo_legal_attack() {
    auto from_bb = bb::from_sq(mi_.from);
    auto to_bb = bb::from_sq(mi_.to);
    if (mi_.from_pc == piece::Pawn) {
        if ((rank_8() & to_bb) != bb::Empty) {
            return false;
        }
        // There should not be any ep move at this point
        if ((single_pushes(from_bb) & to_bb) == bb::Empty &&
            (double_pushes(from_bb) & to_bb) == bb::Empty &&
            (pawn_attacks(from_bb) & color_bb_[!turn_] & to_bb) == bb::Empty) {
            return false;
        }
    } else {
        auto atks = lookup::attacks(mi_.from_pc, mi_.from, all());
        if ((atks & to_bb) == bb::Empty) {
            return false;
        }
    }
    return true;
}

bool Board::is_pseudo_legal_evasion() {
    // We will handle king evasions later in is_legal
    if (mi_.from_pc == piece::King) {
        return true;
    }
    if (bb::popcnt(checkers_) >= 2) {
        return false;
    }
    auto to_bb = bb::from_sq(mi_.to);
    return (to_bb & evasion_mask()) != bb::Empty;
}

bool Board::is_attacked(Square sq, Bitboard attackers_mask) {
    return (attackers_to(sq) & attackers_mask) != bb::Empty;
}

bool Board::king_to_is_attacked(Square ksq) {
    remove_piece(turn_, piece::King, ksq);
    auto atkd = is_attacked(mi_.to, color_bb_[!turn_]);
    add_piece(turn_, piece::King, ksq);
    return atkd;
}

bool Board::castling_possible(Castling c) {
    return castle_flags_ & castle_flags::from_castling(c);
}

bool Board::is_legal_castle(Castling c, const CastlingInfo &ci) {
    if (!castling_possible(c)) {
        return false;
    }
    auto ib = lookup::in_between(ci.king_from, ci.rook_from);
    if ((ib & all()) != bb::Empty) {
        return false;
    }
    auto ib_sq = bb::top_sq(lookup::in_between(mi_.from, mi_.to));
    return !is_attacked(ib_sq, color_bb_[!turn_]);
}

bool Board::is_legal_castle() {
    for (Castling c = 0; c < 4; c++) {
        auto &ci = CASTLING_INFO[c];
        if (mi_.from == ci.king_from && mi_.to == ci.king_to) {
            return is_legal_castle(c, ci);
        }
    }
    return true;
}

bool Board::is_pinned() {
    return (pinned_ & bb::from_sq(mi_.from)) != bb::Empty;
}

bool Board::is_on_line(Square s0, Square s1, Square s2) {
    auto x0 = square::file(s0);
    auto x1 = square::file(s1);
    auto x2 = square::file(s2);
    auto y0 = square::rank(s0);
    auto y1 = square::rank(s1);
    auto y2 = square::rank(s2);
    if (x0 == x1) {
        return x1 == x2;
    }
    if (y0 == y1) {
        return y1 == y2;
    }
    if (x0 + y0 == x1 + y1) {
        return x1 + y1 == x2 + y2;
    }
    if (x0 - y0 == x1 - y1) {
        return x1 - y1 == x2 - y2;
    }
    return false;
}

bool Board::is_legal_ep(Square ksq) {
    auto ep = mi_.to ^ 8;
    move_piece(turn_, piece::Pawn, mi_.from, mi_.to);
    remove_piece(!turn_, piece::Pawn, ep);
    auto atkd = is_attacked(ksq, color_bb_[!turn_]);
    add_piece(!turn_, piece::Pawn, ep);
    move_piece(turn_, piece::Pawn, mi_.to, mi_.from);
    return !atkd;
}

void Board::setup_fen_pieces(std::istringstream &iss) {
    for (auto &pc_bb : piece_bb_) {
        pc_bb = bb::Empty;
    }
    for (auto &cr_bb : color_bb_) {
        cr_bb = bb::Empty;
    }
    for (Rank rk = rank::_8; rk >= rank::_1; rk--) {
        for (File fl = file::A; fl <= file::H; fl++) {
            char c;
            iss >> c;
            if (isdigit(c)) {
                fl += c - '1';
            } else {
                auto pc = piece::from_char(tolower(c));
                if (!pc) {
                    return;
                }
                auto sd = isupper(c) ? color::White : color::Black;
                add_piece(sd, *pc, square::init(rk, fl));
            }
        }
        if (rk > rank::_1) {
            char c;
            iss >> c;  // Consume '/' char
        }
    }
}

void Board::setup_fen_turn(std::istringstream &iss) {
    turn_ = color::White;
    std::string turn;
    iss >> turn;
    if (turn == "b") {
        flip_turn();
    }
}

void Board::add_castle_flags(CastleFlags cfs) {
    hash_ ^= hash::castling[castle_flags_];
    castle_flags_ |= cfs;
    hash_ ^= hash::castling[castle_flags_];
}

void Board::setup_fen_castle_flags(std::istringstream &iss) {
    std::string cfs_str;
    iss >> cfs_str;
    castle_flags_ = castle_flags::None;
    for (auto ch : cfs_str) {
        for (Castling c = 0; c < 4; c++) {
            if (ch == CASTLING_FEN[c]) {
                add_castle_flags(castle_flags::from_castling(c));
            }
        }
    }
}

void Board::setup_fen_ep(std::istringstream &iss) {
    std::string ep_str;
    iss >> ep_str;
    ep_ = file::None;
    if (ep_str != "-") {
        auto sq = square::from_str(ep_str);
        auto fl = square::file(sq);
        set_ep(fl);
    }
}

void Board::setup_fen_halfmove_clock(std::istringstream &iss) {
    i32 hmc;
    iss >> hmc;
    halfmove_clock_ = hmc;
}

void Board::setup_fen_fullmove_cnt(std::istringstream &iss) {
    i32 fmc;
    iss >> fmc;
    fullmove_cnt_ = fmc;
}

bool Board::has_legal_move() {
    return movegen::has_legal_move(*this);
}

bool Board::is_fifty_move_draw() {
    return halfmove_clock_ >= 100 && (!in_check() || has_legal_move());
}

i32 Board::repetition_count() {
    auto reps = 0;
    auto n = undos_.size();
    auto mx = std::min(n, static_cast<size_t>(halfmove_clock_));
    for (auto i = 4; i <= mx; i += 2) {
        if (hash_ == undos_[n - i].hash) {
            reps++;
        }
    }
    return reps;
}

bool Board::is_repetition_draw() {
    return repetition_count() >= 2;
}

Piece Board::color_on(Square sq) {
    return color_bb_[color::White] & bb::from_sq(sq) ? color::White
                                                     : color::Black;
}

char Board::debug_char(Square sq) {
    auto pc_char = piece::to_char(piece_on_[sq]);
    return color_on(sq) == color::White ? toupper(pc_char) : pc_char;
}

}  // namespace tuna::board
