name: Build and Upload Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13

      - name: Install build tools
        run: sudo apt update && sudo apt install -y ninja-build build-essential

      - name: Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        uses: threeal/ctest-action@v1.1.0
        with:
          test-dir: build/test

      - name: Strip binary
        run: strip build/tuna

      - name: Rename binary with tag
        run: mv build/tuna tuna-${{ github.ref_name }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tuna-${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
